// <auto-generated />
using System;
using MediCareMS.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MediCareMS.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260520000001_AddInvitations")]
    partial class AddInvitations
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Minimal designer file - full snapshot is in AppDbContextModelSnapshot.cs
        }
    }
}
